class Autogenerated {
  List<Historytransition>? historytransition;
  bool? status;

  Autogenerated({this.historytransition, this.status});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['historytransition'] != null) {
      historytransition = <Historytransition>[];
      json['historytransition'].forEach((v) {
        historytransition!.add(new Historytransition.fromJson(v));
      });
    }
    status = json['status'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.historytransition != null) {
      data['historytransition'] =
          this.historytransition!.map((v) => v.toJson()).toList();
    }
    data['status'] = this.status;
    return data;
  }
}

class Historytransition {
  int? id;
  String? createdAt;
  String? updatedAt;
  Null? transactionId;
  String? userId;
  String? amount;
  String? status;
  String? point;
  String? name;
  String? paymentMode;
  String? paymentNo;
  String? successDate;
  String? failedDate;

  Historytransition(
      {this.id,
        this.createdAt,
        this.updatedAt,
        this.transactionId,
        this.userId,
        this.amount,
        this.status,
        this.point,
        this.name,
        this.paymentMode,
        this.paymentNo,
        this.successDate,
        this.failedDate});

  Historytransition.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    transactionId = json['transaction_id'];
    userId = json['user_id'];
    amount = json['amount'];
    status = json['status'];
    point = json['point'];
    name = json['name'];
    paymentMode = json['payment_mode'];
    paymentNo = json['payment_no'];
    successDate = json['success_date'];
    failedDate = json['failed_date'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    data['transaction_id'] = this.transactionId;
    data['user_id'] = this.userId;
    data['amount'] = this.amount;
    data['status'] = this.status;
    data['point'] = this.point;
    data['name'] = this.name;
    data['payment_mode'] = this.paymentMode;
    data['payment_no'] = this.paymentNo;
    data['success_date'] = this.successDate;
    data['failed_date'] = this.failedDate;
    return data;
  }
}